spring:
  application:
    name: LivroLog

  datasource:
    url: jdbc:h2:file:./data/meu-banco
    driver-class-name: org.h2.Driver
    username: admin
    password:
    hikari:
      maximum-pool-size: 10
      minimum-idle: 2
      idle-timeout: 300000
      max-lifetime: 600000
      connection-timeout: 30000

  h2:
    console:
      enabled: true
      path: /h2-console

  jpa:
    hibernate:
      ddl-auto: update

